
package gsm0341.nokia;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1BoxedType ( name = "CellIdListDiscBase" )
    public class CellIdListDiscBase implements IASN1PreparedElement {
    
    		public static final byte[] lacAndCi = {(byte) 0x01};
    		public static final byte[] ciOnly = {(byte) 0x02};
    		public static final byte[] allCellsOnBSS = {(byte) 0x06};
    		
            @ASN1OctetString( name = "CellIdListDiscBase" )
            
            @ASN1SizeConstraint ( max = 1L )
        
            private byte[] value = null;
            
            public CellIdListDiscBase() {
            }

            public CellIdListDiscBase(byte[] value) {
                this.value = value;
            }

            public CellIdListDiscBase(BitString value) {
                setValue(value);
            }
            
            public void setValue(byte[] value) {
                this.value = value;
            }

            public void setValue(BitString btStr) {
                this.value = btStr.getValue();
            }
            
            public byte[] getValue() {
                return this.value;
            }

	    public void initWithDefaults() {
	    }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(CellIdListDiscBase.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }


    }
            