
package gsm0341.nokia;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "Cell", isSet = false )
    public class Cell implements IASN1PreparedElement {
            
        @ASN1Element ( name = "disc", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private CellIdDisc disc = null;
                
  
        @ASN1Element ( name = "id", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private CellId id = null;
                
  
        
        public CellIdDisc getDisc () {
            return this.disc;
        }

        

        public void setDisc (CellIdDisc value) {
            this.disc = value;
        }
        
  
        
        public CellId getId () {
            return this.id;
        }

        

        public void setId (CellId value) {
            this.id = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(Cell.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            