
package gsm0341.nokia;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "DisplayMessageQuery", isSet = false )
    public class DisplayMessageQuery implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 2L 
		
	   )
	   
        @ASN1Element ( name = "contentOfDisplay", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Integer contentOfDisplay = null;
                
  @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 65535L 
		
	   )
	   
        @ASN1Element ( name = "messageIdentifier", isOptional =  true , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Integer messageIdentifier = null;
                
  
        @ASN1Element ( name = "currentSerialNo", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private SerialNumber currentSerialNo = null;
                
  
        @ASN1Element ( name = "cellId", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private Cell cellId = null;
                
  
        @ASN1Element ( name = "channelIndicator", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Channel channelIndicator = null;
                
  
        
        public Integer getContentOfDisplay () {
            return this.contentOfDisplay;
        }

        

        public void setContentOfDisplay (Integer value) {
            this.contentOfDisplay = value;
        }
        
  
        
        public Integer getMessageIdentifier () {
            return this.messageIdentifier;
        }

        
        public boolean isMessageIdentifierPresent () {
            return this.messageIdentifier != null;
        }
        

        public void setMessageIdentifier (Integer value) {
            this.messageIdentifier = value;
        }
        
  
        
        public SerialNumber getCurrentSerialNo () {
            return this.currentSerialNo;
        }

        
        public boolean isCurrentSerialNoPresent () {
            return this.currentSerialNo != null;
        }
        

        public void setCurrentSerialNo (SerialNumber value) {
            this.currentSerialNo = value;
        }
        
  
        
        public Cell getCellId () {
            return this.cellId;
        }

        
        public boolean isCellIdPresent () {
            return this.cellId != null;
        }
        

        public void setCellId (Cell value) {
            this.cellId = value;
        }
        
  
        
        public Channel getChannelIndicator () {
            return this.channelIndicator;
        }

        
        public boolean isChannelIndicatorPresent () {
            return this.channelIndicator != null;
        }
        

        public void setChannelIndicator (Channel value) {
            this.channelIndicator = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(DisplayMessageQuery.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            