
package gsm0341.nokia;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "StatusMessageQueryResp", isSet = false )
    public class StatusMessageQueryResp implements IASN1PreparedElement {
            @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		
		min = 0L, 
		
		max = 65535L 
		
	   )
	   
        @ASN1Element ( name = "messageIdentifier", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Integer messageIdentifier = null;
                
  
        @ASN1Element ( name = "oldSerialNumber", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private SerialNumber oldSerialNumber = null;
                
  

       @ASN1PreparedElement
       @ASN1Sequence ( name = "noOfBroadcastsComplList" , isSet = false )
       public static class NoOfBroadcastsComplListSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "cellId", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Cell cellId = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "noOfBroadcastsCompl", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Long noOfBroadcastsCompl = null;
                
  
        
        public Cell getCellId () {
            return this.cellId;
        }

        

        public void setCellId (Cell value) {
            this.cellId = value;
        }
        
  
        
        public Long getNoOfBroadcastsCompl () {
            return this.noOfBroadcastsCompl;
        }

        

        public void setNoOfBroadcastsCompl (Long value) {
            this.noOfBroadcastsCompl = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_NoOfBroadcastsComplListSequenceType;
        }

       private static IASN1PreparedElementData preparedData_NoOfBroadcastsComplListSequenceType = CoderFactory.getInstance().newPreparedElementData(NoOfBroadcastsComplListSequenceType.class);
                
       }

       
                
@ASN1SequenceOf( name = "noOfBroadcastsComplList", isSetOf = false ) 

    
        @ASN1Element ( name = "noOfBroadcastsComplList", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private java.util.Collection<NoOfBroadcastsComplListSequenceType>  noOfBroadcastsComplList = null;
                
  

       @ASN1PreparedElement
       @ASN1Sequence ( name = "failureList" , isSet = false )
       public static class FailureListSequenceType implements IASN1PreparedElement {
                
        @ASN1Element ( name = "cellId", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Cell cellId = null;
                
  
        @ASN1Element ( name = "cause", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private FailureReason cause = null;
                
  
        @ASN1Element ( name = "diagnostic", isOptional =  true , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private DiagnosticInfo diagnostic = null;
                
  
        
        public Cell getCellId () {
            return this.cellId;
        }

        

        public void setCellId (Cell value) {
            this.cellId = value;
        }
        
  
        
        public FailureReason getCause () {
            return this.cause;
        }

        

        public void setCause (FailureReason value) {
            this.cause = value;
        }
        
  
        
        public DiagnosticInfo getDiagnostic () {
            return this.diagnostic;
        }

        
        public boolean isDiagnosticPresent () {
            return this.diagnostic != null;
        }
        

        public void setDiagnostic (DiagnosticInfo value) {
            this.diagnostic = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }

        public IASN1PreparedElementData getPreparedData() {
            return preparedData_FailureListSequenceType;
        }

       private static IASN1PreparedElementData preparedData_FailureListSequenceType = CoderFactory.getInstance().newPreparedElementData(FailureListSequenceType.class);
                
       }

       
                
@ASN1SequenceOf( name = "failureList", isSetOf = false ) 

    
        @ASN1Element ( name = "failureList", isOptional =  true , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private java.util.Collection<FailureListSequenceType>  failureList = null;
                
  
        @ASN1Element ( name = "channelIndicator", isOptional =  true , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private Channel channelIndicator = null;
                
  
        
        public Integer getMessageIdentifier () {
            return this.messageIdentifier;
        }

        

        public void setMessageIdentifier (Integer value) {
            this.messageIdentifier = value;
        }
        
  
        
        public SerialNumber getOldSerialNumber () {
            return this.oldSerialNumber;
        }

        

        public void setOldSerialNumber (SerialNumber value) {
            this.oldSerialNumber = value;
        }
        
  
        
        public java.util.Collection<NoOfBroadcastsComplListSequenceType>  getNoOfBroadcastsComplList () {
            return this.noOfBroadcastsComplList;
        }

        
        public boolean isNoOfBroadcastsComplListPresent () {
            return this.noOfBroadcastsComplList != null;
        }
        

        public void setNoOfBroadcastsComplList (java.util.Collection<NoOfBroadcastsComplListSequenceType>  value) {
            this.noOfBroadcastsComplList = value;
        }
        
  
        
        public java.util.Collection<FailureListSequenceType>  getFailureList () {
            return this.failureList;
        }

        
        public boolean isFailureListPresent () {
            return this.failureList != null;
        }
        

        public void setFailureList (java.util.Collection<FailureListSequenceType>  value) {
            this.failureList = value;
        }
        
  
        
        public Channel getChannelIndicator () {
            return this.channelIndicator;
        }

        
        public boolean isChannelIndicatorPresent () {
            return this.channelIndicator != null;
        }
        

        public void setChannelIndicator (Channel value) {
            this.channelIndicator = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(StatusMessageQueryResp.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            